# Generated by Django 3.2.9 on 2021-12-01 07:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.TextField(max_length=150, null=True)),
                ('first_name', models.TextField(blank=True, max_length=150, null=True)),
                ('last_name', models.TextField(blank=True, max_length=150, null=True)),
                ('direccion', models.TextField(blank=True, max_length=150, null=True)),
                ('telefono', models.TextField(blank=True, max_length=150, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
