# Generated by Django 3.2.9 on 2021-12-01 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20211201_0706'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='direccion',
            field=models.CharField(blank=True, max_length=50, verbose_name='Direccion'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='rut',
            field=models.CharField(blank=True, max_length=50, verbose_name='Rut'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='telefono',
            field=models.CharField(blank=True, max_length=50, verbose_name='Telefono'),
        ),
    ]
